spring.application.name=NoteRAG
server.port=${SERVER_PORT:9000}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true

noterag.chunking.min-target-tokens=300
noterag.chunking.max-target-tokens=800
noterag.chunking.hard-max-tokens=1000
noterag.chunking.overlap-chars=80
