CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    char_count INTEGER NOT NULL,
    token_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE note_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    chunk_index INTEGER NOT NULL,
    heading_path TEXT,
    content TEXT NOT NULL,
    char_count INTEGER NOT NULL,
    token_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_note_chunks_note
        FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
    CONSTRAINT uk_note_chunks_note_chunk_index UNIQUE (note_id, chunk_index)
);

CREATE TABLE embedding_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    model_name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    dimension INTEGER NOT NULL,
    distance_metric TEXT NOT NULL DEFAULT 'cosine',
    base_url TEXT,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_embedding_models_provider_model_dimension UNIQUE (provider, model_name, dimension)
);

CREATE TABLE chunk_embeddings_1024 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_chunk_id BIGINT NOT NULL,
    embedding_model_id BIGINT NOT NULL,
    embedding TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chunk_embeddings_1024_note_chunk
        FOREIGN KEY (note_chunk_id) REFERENCES note_chunks(id) ON DELETE CASCADE,
    CONSTRAINT fk_chunk_embeddings_1024_embedding_model
        FOREIGN KEY (embedding_model_id) REFERENCES embedding_models(id),
    CONSTRAINT uk_chunk_embeddings_1024_note_chunk_model UNIQUE (note_chunk_id, embedding_model_id)
);

CREATE TABLE chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_message_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_sessions_status_supported CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_chat_sessions_last_message_at_id
    ON chat_sessions (last_message_at DESC, id DESC);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL,
    error_code TEXT,
    char_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE,
    CONSTRAINT chat_messages_role_supported CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT chat_messages_status_supported CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT chat_messages_char_count_non_negative CHECK (char_count >= 0)
);

CREATE INDEX idx_chat_messages_session_created_id
    ON chat_messages (session_id, created_at DESC, id DESC);

CREATE TABLE chat_message_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    note_chunk_id BIGINT NOT NULL,
    source_order INTEGER NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_message_sources_message
        FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_message_sources_note_chunk
        FOREIGN KEY (note_chunk_id) REFERENCES note_chunks(id) ON DELETE RESTRICT,
    CONSTRAINT chat_message_sources_source_order_positive CHECK (source_order > 0),
    CONSTRAINT chat_message_sources_message_source_order_unique UNIQUE (message_id, source_order)
);
