CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    char_count INTEGER NOT NULL,
    token_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE note_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    chunk_index INTEGER NOT NULL,
    heading_path TEXT,
    content TEXT NOT NULL,
    char_count INTEGER NOT NULL,
    token_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_note_chunks_note
        FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
    CONSTRAINT uk_note_chunks_note_chunk_index UNIQUE (note_id, chunk_index)
);

CREATE TABLE embedding_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    model_name TEXT NOT NULL,
    dimension INTEGER NOT NULL,
    distance_metric TEXT NOT NULL DEFAULT 'cosine',
    base_url TEXT,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_embedding_models_provider_model_dimension UNIQUE (provider, model_name, dimension)
);

CREATE TABLE chunk_embeddings_1024 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_chunk_id BIGINT NOT NULL,
    embedding_model_id BIGINT NOT NULL,
    embedding TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chunk_embeddings_1024_note_chunk
        FOREIGN KEY (note_chunk_id) REFERENCES note_chunks(id) ON DELETE CASCADE,
    CONSTRAINT fk_chunk_embeddings_1024_embedding_model
        FOREIGN KEY (embedding_model_id) REFERENCES embedding_models(id),
    CONSTRAINT uk_chunk_embeddings_1024_note_chunk_model UNIQUE (note_chunk_id, embedding_model_id)
);
